//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentDetails1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentInfo
    {
        public int Student_Id { get; set; }
        public string Student_Name { get; set; }
        public string Student_Mobile { get; set; }
        public string Student_Address { get; set; }
        public string Student_Dept { get; set; }
    }
}
